export * from "./cloudcomputing.js"
export * from "./drones.js"
export * from "./ia.js"
export * from "./impresion3d.js"
export * from "./IoTList.js"
export * from "./smartphones.js"
export * from "./realidad_aumentada.js"
export * from "./redes5g.js"
